language: csharp
install:
  - nuget restore ./src/DocsScraper.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release ./src/DocsScraper.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/Tests/bin/Release/Tests.dll
branches:
  only:
  - master